//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: Carla.ice
//  Source: Carla.idsl
//
//******************************************************************
#ifndef ROBOCOMPCARLA_ICE
#define ROBOCOMPCARLA_ICE
module RoboCompCarla
{
	struct Posedata
	{
		float tx;
		float ty;
		float tz;
		float rx;
		float ry;
		float rz;
	};
	sequence <Posedata> Fullposedata;
	struct Actor
	{
		int id;
		int carlaid;
		Fullposedata initpose;
		Fullposedata pose;
		string rol;
	};
	sequence <Actor> Actors;
	struct Simulations
	{
		int nsimulation;
		float duration;
		Actors actorlist;
	};
	struct Collision
	{
		bool iscollision;
		float timecollision;
		int actorcollision;
	};
	struct Simresult
	{
		int indice;
		Collision collision;
		bool isbreak;
		Actors actorlist;
	};
	sequence <Simresult> Fullresults;
	struct Results
	{
		bool valid;
		float time;
		Fullresults fullresult;
	};
	interface Carla
	{
		Results getState ();
		void setSimulationParam (Simulations condini);
	};
};

#endif
